version: '3.8'

services:
  postgres:
    env_file:
      - env_file_postgres_template

  uwsgi:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        REPO_DOWNLOADER_ENABLED: ${REPO_DOWNLOADER_ENABLED}
    image: honeynet/greedybear:ci
    env_file:
      - env_file_app_ci

  celery_beat:
    image: honeynet/greedybear:ci
    env_file:
      - env_file_app_ci

  celery_worker_default:
    image: honeynet/greedybear:ci
    env_file:
      - env_file_app_ci

volumes:
  postgres_data:
  generic_logs:
  shared_files:
