name: Pull request automation

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install -r test-requirements.txt

    - name: Black formatter
      run: |
        black . --check --diff

    - name: Lint with flake8 (PEP8 enforcer + linter)
      run: |
        flake8 . --config=.flake8 --show-source

    - name: isort
      run: |
        isort . --profile black --filter-files --check-only --diff --skip venv